### ISSUE TITLE
Give the caller of decode_without_bom_handling_and_without_replacement the ability to distinguish between Invalid and Incomplete sequences. 

### ISSUE THREAD

**Issue by oshaboy** [hsivonen/encoding_rs#117]
Yes I know you'll probably need to implement another decode function to not make a breaking change to the API. But the program I want to write relies on knowing the difference between invalid and incomplete sequences. 

If the difference isn't clear, Incomplete sequences are the first few bytes of a valid character while Invalid sequences aren't. Like in Shift-JIS-0208 0x90 is an incomplete character (because it starts a 2 byte character) while 0x80 is invalid. 

My preferred API would be something like 
```
enum DecodeError {
    INVALID_CHARACTER,
    INCOMPLETE_CHARACTER
}
decode_with_result<'a>(
    &'static self,
    bytes: &'a [u8]
) -> Result<Cow<'a, &str>, DecodeError>
```
But I don't really care about the specifics. 

ICU actually distinguishes between characters being Invalid and being Illegal but I am not sure what the difference is.

**Comment by hsivonen** [comment]
What's the use case? (The Encoding Standard does not make this distinction.)

**Comment by oshaboy** [comment]
Well I wanted to create mapping files out of encodings by just trying every bytes and then trying every 2 bytes where the byte resulted in an incomplete encoding and so on. 

While the encoding standard doesn't make this distinction it DOES have "encoder state". So a `get_encoder_state` function would be enough.
