### ISSUE TITLE
Don't include test_data in published packages

### ISSUE THREAD

**Issue by retep998** [hsivonen/encoding_rs#21]
The test data is only needed when running tests, and when people get the package off of crates.io they just want to depend on `encoding_rs`, they don't want to run its tests. Removing it would reduce the size of the resulting `.crate`.

**Comment by hsivonen** [comment]
It's a bit unfortunate that the test data makes the crate distributed via crates.io larger, but at least [cargobomb](https://github.com/rust-lang-nursery/cargobomb) makes use of unit tests from crates.io crates, so it's useful for unit tests to work in the context of whatever is distributed via crates.io.

Closing this without action for that reason. Sorry.
