### ISSUE TITLE
Support replacement as label for the replacement encoding

### ISSUE THREAD

**Issue by annevk** [hsivonen/encoding_rs#22]
See https://github.com/whatwg/encoding/issues/70.

(Does there need to be an equivalent Mozilla Bugzilla entry or is this the way to go?)

**Comment by hsivonen** [comment]
Thank you. [Gecko bug 1372230](https://bugzilla.mozilla.org/show_bug.cgi?id=1372230) already covers importing the code changed here into m-c. I filed [Gecko bug 1385836](https://bugzilla.mozilla.org/show_bug.cgi?id=1385836) for removing all the C++-side special cases that'll become obsolete once this change makes it to m-c.
