### ISSUE TITLE
Excessive copying

### ISSUE THREAD

**Issue by SoniEx2** [hsivonen/encoding_rs#28]
The web browser in 1999 could run on 16MB of RAM.

The web browser in 2018 needs 2GB of RAM.

This is mainly caused by excessive copying. Excessive copying is good in languages such as C and C++ where you can't guarantee the lifetimes of pointers, but this is *Rust*. We shouldn't need to copy everything all the time.

The fix? `Cow<str>` is a nice one, and what I'd recommend.

Software should go back to being efficient and fast. Excessive copying is NOT the way to go.

**Comment by jdm** [comment]
Can you point at specific pieces of code that demonstrate excessive copying?

**Comment by SoniEx2** [comment]
Every time you take an &[u8] and put out String instead of Cow<str>.

**Comment by BurntSushi** [comment]
@SoniEx2 Which functions? Can you link to them?

**Comment by SoniEx2** [comment]
I'm asking you to deviate from the encoding standard and not use straight-up String like it recommends, but use a Cow\<str> instead because that's more memory-efficient (and in this case just as safe).

**Comment by hsivonen** [comment]
> The web browser in 1999 could run on 16MB of RAM.
>
> The web browser in 2018 needs 2GB of RAM.

This is uncalled for considering that encoding_rs reduced the RAM footprint (both by making the shared object size smaller and by avoiding copying in certain situations) compared to the code from 1999 (and early 2000) that encoding_rs replaced in Firefox.

> Every time you take an &[u8] and put out String instead of Cow<str>.

As far as I can tell, encoding_rs has no API that returns a `String`. The non-streaming API already returns `Cow`s. If there's a specific concern that I'm missing, please point to a specific function/method.

The streaming API has methods that take an `&mut String` as an _argument_. That API surface exists mainly to accommodate callers originally written for rust-encoding such that `unsafe` stays within encoding_rs and doesn't spill over to the caller.
