### ISSUE TITLE
Decoding invalid input panics when output buffer is too short

### ISSUE THREAD

**Issue by sinkuu** [hsivonen/encoding_rs#32]
```rust
let mut buf = vec![0; 2];
let _ = UTF_8
    .new_decoder()
    .decode_to_utf8(&b"\xFF\xFE\xC4\x64"[..], &mut buf[..], true);
```

This code panics at [src/handles.rs:277:31](https://github.com/hsivonen/encoding_rs/blob/2ecd052d2449b48ece5c3d7d240eed669a9168fc/src/handles.rs#L277) (in release mode, panics at the array indexing after that).

**Comment by hsivonen** [comment]
Sorry about the delay in fixing.

For future reference, this was fixed by commit 07e5b8dd19c4fda23a5d9a99d938504e9b82f6ea and release 0.8.7.
