### ISSUE TITLE
Enhancement: get read access to the decoder's inner state

### ISSUE THREAD

**Issue by getreu** [hsivonen/encoding_rs#48]
This is also about [Stringsext, a GNU Strings Alternative with Multi-Byte-Encoding Support](https://github.com/getreu/stringsext) which I migrated from [rust-encoding](https://github.com/lifthrasiir/rust-encoding) to [encoding_rs](https://github.com/hsivonen/encoding_rs/).

In order to keep anchors between the input and the output stream, I would need to know - when the decoder finished - if it has still some bytes stored in its inner state. The best would be to know how many bytes are hold back, but even the information that there are any would help already.

Is there a way to access this information?

**Comment by hsivonen** [comment]
By definition, the decode hasn't finished if you haven't called the decoder with `last=true` and gotten `InputEmpty` as the result.

However, if you have a `Decoder` called `decoder`, you can ask for `decoder.max_utf8_buffer_length_without_replacement(0)` to get the worst-case estimate of the pending output.

**Comment by getreu** [comment]
This is not my problem:
when get a decoded junk `&s1`, I need to know the exact byte position of the corresponding chunk in the input stream. My problem: where does the first character of `&s1` belongs to? This or the previous input chunk?

The only solution I found so far, is to decode the input junk a second time with a newly initialized decoder. Then, I compare the second result `&s2` with `&s1`. Only when they are equal, I can be sure that the first character of `&s1` originates from the first byte of the input chunk.

It is obvious, that decoding the same chunk twice is far from being optimal. How can know if the decoder holds some bytes back?

**Comment by hsivonen** [comment]
> How can know if the decoder holds some bytes back?

For decoders other than `replacement`, `UTF-16BE` and `UTF-16LE` that are created without BOM handling, the decoder is not in a neutral state if `decoder.latin1_byte_compatible_up_to(b"").is_none()` is `true`.

There is no way to check this for `replacement`, `UTF-16BE` and `UTF-16LE`. (They always return `None`.)

**Comment by getreu** [comment]
Thank you. This is (partly) good news!

> For decoders other than
> 1. `replacement`,

not used in `Strindsext`

> 2. `UTF-16BE` and `UTF-16LE`

heavily used in `Stringsext`,

> 3. that are created without BOM handling,

BOM handling is not used in `Stringsext`.

Constraints 1. and 3. are no problem for `Stringsext`, but constraint 2. actually is:
UTF-16BE/LE is one of the most important encoding in memory forensics.

Is there another way of checking neutral state for `UTF-16BE/LE`?

**Comment by getreu** [comment]
A second question to prevent misunderstanding: Is the contrary also right?

The decoder **is** in a neutral state if 
`decoder.latin1_byte_compatible_up_to(b"").is_some()` is true?

**Comment by getreu** [comment]
Ok, I tested, if with `decoder.latin1_byte_compatible_up_to(b"").is_none()` I can at least reduce the number of double decoding. Surprisingly, it turned out, that `decoder.latin1_byte_compatible_up_to()` is more time expensive than decoding twice by default.

It seems to me, that the only way to improve Stingsext is, to add a method to `encoding_rs` giving fast read access to the decoder's inner state.

Could you see this as a future enhancement of `encoding_rs` API?

**Comment by hsivonen** [comment]
> The decoder is in a neutral state if `decoder.latin1_byte_compatible_up_to(b"").is_some()` is true?

Yes, that's always true. Additionally, `UTF-16BE`, and `UTF-16LE` may be in a neutral state even if that's not true. `replacement` is conceptually unusual in relation to the question.

> Surprisingly, it turned out, that `decoder.latin1_byte_compatible_up_to(b"")` is more time expensive than decoding twice by default.

That's really surprising. How long is the input you are decoding?

> It seems to me, that the only way to improve Stingsext is, to add a method to encoding_rs giving fast read access to the decoder's inner state.

When the slice argument has no bytes to examine, that's what `latin1_byte_compatible_up_to` does. It seems very odd that the check for the slice length and bailing out when zero could be so expensive.

> Could you see this as a future enhancement of encoding_rs API?

I'd like to understand the use case a bit better. If you checked the documentation for `latin1_byte_compatible_up_to` it already advises against using it except for a very specific situation when doing low-level work with the kind of string representation that SpiderMonkey and V8 have.

But if the use case seems to outweigh the footgun/misuse risk of such an API, it should be possible to add the neutral state check to UTF-16BE and UTF-16LE and then to expose it and the check that the other encodings already use internally as part of the implementation of `latin1_byte_compatible_up_to`. But it's really hard to believe that the solution would be faster than `latin1_byte_compatible_up_to(b"")` for the encodings that already support the `latin1_byte_compatible_up_to(b"")` approach.

**Comment by getreu** [comment]
> > Surprisingly, it turned out, that `decoder.latin1_byte_compatible_up_to(b"")` is more time expensive than decoding twice by default.
> 
> That's really surprising. How long is the input you are decoding?

Just 8 bytes. In terms of correctness [my following workaround (line 213)](https://github.com/getreu/stringsext/blob/master/src/scanner.rs) is not perfect, because it can return wrong results. There is a trade-off between speed and correctness. 

```rust
if decoder_input_start == 0 && starts_with_multibyte_char(output_buffer_slice) {
     let mut empty_decoder =
         ss.decoder.encoding().new_decoder_without_bom_handling();
     let mut buffer_bytes = [0u8; 8];
     let buffer: &mut str = as_mut_str_unchecked_no_borrow_check!(buffer_bytes[..]);
     let (_, _, written) = empty_decoder.decode_to_str_without_replacement(
         &input_buffer[..],
         &mut buffer[..],
         true,
     );

     if (written == 0)
         || (fc.output_buffer_bytes[0..written] != buffer_bytes[0..written])
     {
         position_precision = Precision::Before;
     }
}
```

When I replaced the first line with 

```rust
if decoder_input_start == 0 && decoder.latin1_byte_compatible_up_to(b"").is_none() && starts_with_multibyte_char(output_buffer_slice) {
```
`Stringsext` got 5-10% slower. Anyway, I am really unhappy with the above workaround: What I actually need to know is: *Does the first decoded character in `output_buffer` originate from the last `decode_to_str()` run or from the run before? Where did it exactly start?*

The idea: with something like `decoder.state_has_pending_bytes()` I could faster and faultless identify pending bytes in the decoder's inner state.

The next step then would be: 
* `!decoder.state_has_pending_bytes()` && next `decode_to_str()` returns some characters `s`
   -> the first decoded character in `s` starts in its original encoding exactly at `decoder_input_start`.
* `decoder.state_has_pending_bytes()` && next `decode_to_str()` returns some characters `s`
   -> the first character in `s` originates form the penultimate `decode_to_str()` run (== starts *before* `decoder_input_start`).
* `decoder.state_has_pending_byte()`  && next  `decode_to_str()` returns `DecoderResult::Malformed` 
  -> Inner state is cleared, no bytes pending. Run `decode_to_str()` again.

> When the slice argument has no bytes to examine, that's what `latin1_byte_compatible_up_to` does. It seems very odd that the check for the slice length and bailing out when zero could be so expensive.

Yes, it surprised me also. Maybe it is because it is in the inner loop. There every additional instruction/redirection counts.

> I'd like to understand the use case a bit better. If you checked the documentation for `latin1_byte_compatible_up_to` it already advises against using it except for a very specific situation when doing low-level work with the kind of string representation that SpiderMonkey and V8 have.

Yes, I had a look. It is not clear to me how the relation with the inner state is. Your explanation is 
clear and precise though.

> But if the use case seems to outweigh the footgun/misuse risk of such an API, it should be possible to add the neutral state check to UTF-16BE and UTF-16LE and then to expose it and the check that the other encodings already use internally as part of the implementation of `latin1_byte_compatible_up_to`. But it's really hard to believe that the solution would be faster than `latin1_byte_compatible_up_to(b"")` for the encodings that already support the `latin1_byte_compatible_up_to(b"")` approach.

As mentioned above, I do not understand how this function interacts with the inner state. What I would need for my use-case is something like `decoder.state_has_pending_bytes()`.

--
BTW the algorithm in the listing above is not always correct, because:

1. `starts_with_multibyte_char(output_buffer_slice)` might not cover all cases, where the decoder is potentially in a not neutral state (especially with UTF-16). 
2. Comparing only 8 bytes of output, does not 100% guarantee, that no bytes originate from the decoder's inner state memory.
