### ISSUE TITLE
Feature Request: Support IBM OEM code pages (e.g. CP437)

### ISSUE THREAD

**Issue by tats-u** [hsivonen/encoding_rs#51]
IBM OEM code pages live on today, persistently in zip archive file names, for example.
OEM code pages of (South)east asian languages are same as ANSI code pages, included in this library now, but other languages including European languages are not.

Code pages list (OEM codepages are included): https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers?source=docs
Characters list (CP437; replace 437 for other code pages): https://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/PC/CP437.TXT

**Comment by hsivonen** [comment]
This crate is [explicitly](https://github.com/hsivonen/encoding_rs/blob/master/CONTRIBUTING.md#no-encodings-beyond-the-encoding-standard) scoped to the Encoding Standard.

However, another crate could support more encoding such that operations on the encodings that _are_ in the Encoding Standard are delegated to this crate and extra encodings are implemented by the wrapper crate itself.

**Comment by tats-u** [comment]
I got it.  I will create it by myself.

**Comment by tats-u** [comment]
I did it:
https://github.com/tats-u/rust-oem-cp

**Comment by hsivonen** [comment]
Nice! I [added](https://github.com/hsivonen/encoding_rs/commit/ab1a2d213616155dc2323a280c4e2b7896723526) links to the documentation of this crate.

**Comment by tats-u** [comment]
@hsivonen Thank you for the quick response.
