### ISSUE TITLE
release a binary to compete with iconv?

### ISSUE THREAD

**Issue by seamusabshere** [hsivonen/encoding_rs#59]
hey, have you guys considered releasing a binary to compete with iconv? looks like you'd beat the one in ubuntu 18 by 4x.

**Comment by hsivonen** [comment]
There's [`recode_rs`](https://crates.io/crates/recode_rs), which addresses the same problem domain as `iconv` and has compatible command-line options. However, it doesn't implement all the command-line options that `iconv` implements.
