### ISSUE TITLE
gbk/gb18030 private use codepoint can be decode and encode 

### ISSUE THREAD

**Issue by xiongjiwei** [hsivonen/encoding_rs#76]
for example [0xE4C6](https://github.com/whatwg/encoding/blob/be3337450e7df1c49dca7872153c4c4670dd8256/index-gb18030.txt#L6087), it is private use, `encoding_rs` will encode this codepoint to `0xA140`.

Is this expected?

**Comment by hsivonen** [comment]
Yes, this is expected. gbk/gb18030 provide explicit mappings for a number of private-use characters to fill the whole gbk encoding space with assigments. The GB18030 standard even assigns semantics to a handful of code points that are private-use in Unicode terms.
