### ISSUE TITLE
Provide a way to manually set the encoding of a Decoder

### ISSUE THREAD

**Issue by dralley** [hsivonen/encoding_rs#84]
I'm working on an XML parsing library.  XML generally provides an encoding name in the header [0], which avoids the need to use heuristics for single-byte encodings.  Additionally if you know that XML documents generally start with the character `<` then you can improve the heuristic for detecting endian-ness without a BOM.

[0] e.g. `<?xml version="1.0" encoding="Shift_JIS">...."`

Therefore it would be nice to provide a way to manually override the encoding at runtime in the same way that the sniffing otherwise might.

**Comment by hsivonen** [comment]
If you start with one encoding and then want to override in the middle, it's a problem if the first decoder already saw a buffer that went past the end greater-than sign of the XML declaration. I suggest:
1. Buffer 3 bytes.
2. Apply `Encoding::from_bom()`
3. If `None` and the first two bytes were `b"<?"`, buffer up to and including the first greater-than sign and then apply [`xmldecl::parse`](https://docs.rs/xmldecl/latest/xmldecl/fn.parse.html).
4. On the actual post-decode XML parsing layer, check that the XML declaration was actually well-formed.
