### ISSUE TITLE
A list of all characters that specific encoding can represent?

### ISSUE THREAD

**Issue by Mingun** [hsivonen/encoding_rs#85]
I making tests for [quick-xml](https://github.com/tafia/quick-xml) and I want to test our support of differently-encoded documents. Ideally, I want to test documents with all possible characters that can be encoded by a specific encoding. Because 30 of 40 supported encodings of this crate is a single-byte encodings, there not so much symbols that each document could have. Also it is easy to generate all possible symbols for these encodings, just by decoding bytes from `0..256_u8` range.

The other 6 (UTF-8, UTF-16BE, UTF-16LE is a special case, REPLACEMENT is not an encoding actually) is a multi-byte encodings and I need to know which characters they can encode. Because encodings actually built on the encoding tables, it would be worths if `encodng_rs` could expose these tables in some way, maybe under a feature flag. Then I could take some (if not all) symbols from that tables and put them into my test files.

Do you think that adding such an API could be useful?

**Comment by hsivonen** [comment]
I think test data generation is outside the scope of the crate itself. However, the [code generation script](https://github.com/hsivonen/encoding_rs/blob/master/generate-encoding-data.py) has such test data generation code in Python 2. (Since this is the first Rust crate that I wrote, I wrote the code generation part in Python 2 and not in Rust itself, which, in retrospect, is unfortunate.)

**Comment by Mingun** [comment]
Actually, task not in test data generation, but getting an iterator over all supported codepoints of the encoding (and maybe a check that some codepoint can be encoded by a specific encoding). Probably there a some tasks where such knowledge will be useful. If it is not hard to implement such methods then why not?

So if it is hard to implement, you can close this issue. Yeah, I looked into your script and visualization scripts in [encoding](https://github.com/whatwg/encoding) to get a list of these codepoints.

**Comment by hsivonen** [comment]
`Encoder` already has [`_without_replacement`](https://docs.rs/encoding_rs/latest/encoding_rs/struct.Encoder.html#method.encode_from_utf8_without_replacement) methods that allow checking if a character can be encoded.

For single-byte and two-byte encodings as well as EUC-JP, its reasonably easy to iterate over all possible input byte ranges to see what decodes.
